# Generated by Django 3.2.8 on 2021-11-10 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='std_name',
            new_name='name',
        ),
    ]
