# Generated by Django 3.2.8 on 2021-11-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_students_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='skills',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
