# Generated by Django 3.2.8 on 2021-11-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_teacher_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cart',
            field=models.TextField(),
        ),
    ]
