# Generated by Django 3.2.8 on 2021-11-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_student_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='author_name',
            new_name='Teacher_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='courses',
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_pic',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=25),
        ),
    ]
