# Generated by Django 3.2.8 on 2021-11-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20211103_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profession',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='profession',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
