# Generated by Django 3.2.8 on 2021-11-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20211103_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='std_name',
            field=models.CharField(max_length=150),
        ),
    ]
