# Generated by Django 3.2.8 on 2021-11-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_cart_std_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cart',
        ),
    ]
