# Generated by Django 3.2.8 on 2021-11-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_student_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='courses',
            field=models.CharField(default=1, max_length=150),
        ),
    ]
