# Generated by Django 3.2.8 on 2021-11-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_cart_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='courses',
            field=models.CharField(max_length=150),
        ),
    ]
