# Generated by Django 3.2.8 on 2021-11-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_cart_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='category',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
